<a href="https://colab.research.google.com/github/SaadARazzaq/Numpy-22/blob/main/22_Numpy_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **22 Numpy Problems**

In [1]:
import numpy as np

In [5]:
# Task 1: Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
indices = np.nonzero([1,2,0,0,4,0])
indices

(array([0, 1, 4]),)

In [6]:
# Task 2:  Create a null vector of size 10 (★☆☆)

null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# Task 3:  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

null_vector_1 = np.zeros(10)
null_vector_1[4] = 1
null_vector_1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
# Task 4:   Create a vector with values ranging from 10 to 49 (★☆☆)

range_vector = np.arange(10, 50)
range_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
# Task 5:   Reverse a vector (first element becomes last) (★☆☆)

reverse_range_vector = range_vector[::-1]
reverse_range_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [20]:
# Task 6:   Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

matrx = np.array(0,8,size=(3,3))
matrx

TypeError: ignored

In [21]:
# Task 6:   Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

matrx = np.arange(9).reshape(3,3)
matrx

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
# Task 7:   Find indices of non­zero elements from [1,2,0,0,4,0]  (★☆☆)

indeces = np.nonzero([1,2,0,0,4,0])
indeces

(array([0, 1, 4]),)

In [23]:
# Task 8:   Create a 3x3 identity matrix (★☆☆)

identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# Task 9:    Create a 3x3x3 array with random values (★☆☆)

random_3_by_3 = np.random.random((3,3,3))
random_3_by_3

array([[[0.84225017, 0.12603424, 0.73447569],
        [0.16807332, 0.7958127 , 0.38704429],
        [0.86452566, 0.61649232, 0.38274686]],

       [[0.70294829, 0.46573608, 0.50099556],
        [0.07237415, 0.76020934, 0.40990864],
        [0.75209582, 0.50090109, 0.42552872]],

       [[0.82724987, 0.12422325, 0.93663202],
        [0.7886167 , 0.43169873, 0.70004669],
        [0.74225203, 0.46820634, 0.65362681]]])

In [36]:
# Task 10:    Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

random_10_by_10 = np.random.random((10,10))
print(random_10_by_10)
maximum = np.max(random_10_by_10)
print("Max is: ", maximum)
minimum = np.min(random_10_by_10)
print("Min is: ", minimum)

[[0.15950214 0.24530811 0.94488352 0.17220997 0.82843678 0.210502
  0.88777132 0.81744212 0.88893287 0.98828901]
 [0.66089703 0.27393209 0.31861176 0.94320282 0.77214781 0.91174486
  0.64571044 0.31988415 0.37900582 0.22543148]
 [0.82992515 0.34188241 0.96022099 0.17395528 0.34841825 0.95985456
  0.15123238 0.56162072 0.01021538 0.9261366 ]
 [0.68538537 0.032321   0.74201623 0.92393503 0.13741125 0.35999076
  0.84275421 0.80942278 0.85897861 0.36368973]
 [0.45216073 0.06548261 0.35037505 0.62181033 0.65683599 0.92901747
  0.08560043 0.68573729 0.55209309 0.01475686]
 [0.64945254 0.81332408 0.3287336  0.59628681 0.91320459 0.21865406
  0.47944319 0.22502983 0.68047451 0.11420541]
 [0.4866918  0.17239027 0.6482931  0.78000509 0.00403466 0.75571292
  0.01101424 0.46610915 0.07927961 0.63333323]
 [0.53070528 0.11027653 0.07735586 0.41791384 0.66454785 0.17891334
  0.94507396 0.12596839 0.60475506 0.66865444]
 [0.23870159 0.97126653 0.1440631  0.83750196 0.32556471 0.06266491
  0.95022655 0

In [38]:
# Task 11:     Create a random vector of size 30 and find the mean value (★☆☆)

random_size_30_vector = np.random.random(30)
print(random_size_30_vector)
print("Mean is: ", np.mean(random_size_30_vector))

[0.34242172 0.25596002 0.41703114 0.25776579 0.48034313 0.33991531
 0.97967803 0.1094314  0.48826461 0.73843583 0.3162656  0.06701002
 0.41342284 0.12756518 0.19391448 0.55401138 0.60259062 0.26431782
 0.78636041 0.8248226  0.93637237 0.32541418 0.39227423 0.27903943
 0.97691816 0.31318824 0.88022451 0.8253603  0.99715957 0.08076718]
Mean is:  0.48554153673621564


In [76]:
# Task 12:      Create a 2d array with 1 on the border and 0 inside (★☆☆)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [77]:
# Task 13:      Create a 2d array with 0 on the border and 1 inside (★☆☆)

Z = np.zeros((10,10))
Z[1:-1,1:-1] = 1
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
# Task 15. What is the result of the following expression? (★☆☆)

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [87]:
# Task 16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

m = np.diag(np.arange(4)+1,k=-1)
m

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [92]:
# Task 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [101]:
# Task 18. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

m1 = np.random.random((5,3))
m2 = np.random.random((3,2))
print("Matrix 1: ")
print(m1)
print("Matrix 2: ")
print(m2)
print("Dot Product: ")
print(m1 @ m2)

Matrix 1: 
[[0.17456868 0.82437942 0.35879511]
 [0.64778222 0.59463196 0.80879475]
 [0.82268364 0.47258023 0.08379983]
 [0.57174856 0.90693423 0.94514479]
 [0.37152221 0.8110939  0.45343184]]
Matrix 2: 
[[0.51961424 0.03136821]
 [0.79292937 0.2467039 ]
 [0.80900709 0.09275422]]
Dot Product: 
[[1.03465081 0.24213328]
 [1.46241869 0.24203692]
 [0.86999553 0.15016629]
 [1.78085232 0.32934511]
 [1.20301798 0.25381173]]


In [109]:
# Task 19.  Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

matrx = np.random.choice(5,size=(5,5))
matrx

array([[1, 4, 2, 4, 4],
       [0, 3, 4, 0, 0],
       [0, 3, 0, 4, 0],
       [0, 3, 0, 0, 4],
       [2, 3, 2, 4, 1]])

In [116]:
# Task 20. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

def generator():
  for x in range(10):
    yield x

a = np.array(list(generator()))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
# Task 21. How to get the diagonal of a dot product? (★★★)

m1 = np.random.random((2,2))
m2 = np.random.random((2,2))
print("Matrix 1: ")
print(m1)
print("Matrix 2: ")
print(m2)
print("Dot Product: ")
d = m1 @ m2
print(d)

print("Diagonal of Dot Product: ")
print(np.diag(d))

Matrix 1: 
[[0.21893892 0.25763424]
 [0.63971879 0.72898918]]
Matrix 2: 
[[0.74968277 0.90153021]
 [0.51703392 0.06387291]]
Dot Product: 
[[0.29734038 0.2138359 ]
 [0.85649829 0.62328848]]
Diagonal of Dot Product: 
[0.29734038 0.62328848]


In [119]:
# Task 22.  Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi - yj))

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973
